stages:
  - test
  - train
  - docker-build

variables:
  IMAGE_NAME: "phishing-detection-ml"
  CONTAINER_IMAGE: "$CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
  CONTAINER_LATEST_IMAGE: "$CI_REGISTRY_IMAGE/$IMAGE_NAME:latest"

before_script:
  - python --version

# -------------------------
# TEST STAGE
# -------------------------
test-job:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements/dev.txt
    - python -c "from api.main import app"
    - echo "FastAPI import validation successful"

# -------------------------
# TRAINING STAGE
# -------------------------
training-job:
  stage: train
  image: python:3.11
  when: manual
  script:
    - pip install -r requirements/dev.txt
    - python -m src.training.pipeline

# -------------------------
# DOCKER BUILD STAGE
# -------------------------
docker-build-job:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"    
  before_script:
    - docker version
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $CONTAINER_IMAGE -t $CONTAINER_LATEST_IMAGE .
    - docker images
    - docker push $CONTAINER_IMAGE
    - docker push $CONTAINER_LATEST_IMAGE